feat: upgrade astro to version 3
ixartz/Astro-boilerplate pull request #14
Opened 2023-10-13 01:31 UTC by javleds

Changelog:
- Upgrade dependencies to run over astro v3.
- Remove experimental features (robots working as expected on new astro versions).

2023-10-13 15:06 UTC, ixartz requested changes
Just a few comments. Otherwise, it looks good to me.

Thank you for making the PR.

2023-10-13 15:06 UTC, ixartz commented on package.json
> +    "path-browserify": "^1.0.1",
Why path-browserify is needed?

2023-10-13 15:06 UTC, ixartz commented on package.json
> +  "author": "Javier Ledezma <juls0593@gmail.com>"
Could you revert the change here

2023-10-13 15:09 UTC, javleds commented on package.json
> +  "author": "Javier Ledezma <juls0593@gmail.com>"
My apologies, we will revert this one.

2023-10-13 17:06 UTC, javleds commented on package.json
> +    "path-browserify": "^1.0.1",
`path-browserify` is required for the `rss` plugin, please see:

<img width="679" alt="Screenshot 2023-10-13 at 10 37 20" src="https://github.com/ixartz/Astro-boilerplate/assets/11241239/b87092f9-0d5e-4e90-99e8-a13f7700bd96">

2023-10-13 19:48 UTC, ixartz commented on package.json
> +    "path-browserify": "^1.0.1",
Ok perfect, thank you

2023-10-13 19:49 UTC, ixartz commented
It looks good to me, can I merge?

2023-10-13 19:58 UTC, javleds commented
> Thank you for making the change, it looks good to me, can I merge?

Hi @ixartz , for sure PR is finished now. Thank you.

2023-10-14 16:39 UTC, ixartz approved these changes

2023-10-14 16:39 UTC, merged

2023-10-14 16:39 UTC, ixartz commented
@javleds Thank you for making this PR